language: python
sudo: true
python:
    - "3.2"

install:
    - bash test/setup_test.sh

script:
    # so to help eventual debug: knowing what exact versions are in use can be rather useful.
    - pip freeze

    # Code static analysis
    - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' pycmake/*

    # Coverage and tests
    - coverage erase
    # - cd test/
    - nosetests -xv --nologcapture --with-coverage --cover-package=pycmake test/*.py
    - coverage combine
    - ls -la
    - cat .coverage
    - coverage report -m

after_success:
    - coveralls -v
