language: python
sudo: true
dist: trusty
python:
    - "2.7"
    - "3.5"

install:
    - bash test/setup_test.sh

script:
    # so to help eventual debug: knowing what exact versions are in use can be rather useful.
    - pip3 freeze

    # Code static analysis
    - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402,W503' pycmake/*

    # Coverage and tests
    - rm -fr pycmake/__pycache__
    - pylint --rcfile=.pylintrc pycmake/*
    - cd test/
    - nosetests -xv --nologcapture --with-coverage --cover-package=pycmake test_*.py
    - coverage combine
    - coverage report -m
    - cp .coverage ../
    - cd ..

after_success:
    - coveralls -v
